---
title: "Homework_8"
output: html_document
date: "2025-02-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#Load tidyverse
library(tidyverse)

#Load the iris dataset
data(iris)

#1. Examine structure of the iris dataset
glimpse(iris)
dim(iris) #Check the number of observations and variables

#2. Create iris 1: filter for species "virginica" and "versicolor with Sepal.Length >6 and Sepal.Widths >2.5
iris1 <- iris%>%
  filter(Species %in% c("virginica", "versicolor"),
    Sepal.Length > 6,
    Sepal.Width > 2.5)
    
dim(iris1) #check dimensions of iris1

#3. Create iris2: select only Species, Sepal.Length, and Sepal. Width
iris2 <- iris1 %>%
  select(Species, Sepal.Length, Sepal.Width)
dim(iris2) #check dimensions of iris2

#4. Create iris3: arrange by Sepal.length in descending order
iris3 <- iris2 %>%
  arrange(desc(Sepal.Length))
head(iris3) #display the first 6 rows

#5. Create iris4: Add a new colun Sepal.Area (Sepal.Length *Sepal.Width)
iris4 <- iris3 %>%
  mutate(Sepal.Area = Sepal.Length * Sepal.Width)
dim(iris4) #Check dimensions of iris4 

#6. Creae iris5: Summarize to get mean Sepal.Length, mean Sepal. Width, and sample size
iris5 <- iris4 %>%
  summarize(
    Avg_Sepal_Length = mean(Sepal.Length),
    Avg_Sepal_Width = mean(Sepal.Width),
    Sample_Size = n()
  )
print(iris5)

#7. Create iris6: Group by species and summarize mean Sepal.Length, meanS epal.Width, and sample size
iris6 <- iris4 %>%
  group_by(Species) %>%
  summarize(
    Avg_Sepal_Length = mean(Sepal.Length),
    Avg_Sepal_Width = mean(Sepal.Width),
    Sample_Size = n()
  )
print(iris6)

#8. rewrite steps using piping to create irisFinal
irisFinal <- iris %>%
  filter(Species %in% c("virginica", "versicolor"),
         Sepal.Length > 6,
         Sepal.Width > 2.5) %>%
  select(Species, Sepal.Length, Sepal.Width)%>%
  arrange(desc(Sepal.Length)) %>%
  mutate(Septal.Area =Sepal.Length * Sepal.Width)
dim(irisFinal) #Check dimensions of irisFinal

#9. Create a "longer" format data frame with three columns: Species, Measure, and Value

iris_long <- iris %>%
  pivot_longer(cols = c(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width),
               names_to = "Measure",
               values_to = "Value")
head(iris_long) #Display first 6 rows of the longer dataset

  
```


