---
title: "Homework_3"
output: html_document
date: "2025-02-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

#1
<div style="border: 2px solid black; padding: 10px; display: inline-block;">
$$
Find:\s\{2,\quad\}
$$

$$
\text{Replace :} \quad \text{,}
$$
</div>

Explanation:
This looks for two or more consecutive white spaces or tabs and replaces it with a comma


#2
<div style="border: 2px solid black; padding: 10px; display: inline-block;">

$$
Find: ([A-Za-z]+),\quad\ \s*([A-Za-z]+),\quad\ \s*(.*)
$$


$$
Replace: \2\quad\ \1\quad\ (\3)
$$
</div>

Explanation:
This captures the last name, first name, and institution from a comma-separated format, allowing for flexible spaces. The replacement reorders the first name and last name while placing the institution inside parentheses

#3

<div style="border: 2px solid black; padding: 10px; display: inline-block;">
$$
Find: (\d\{4\}.*?\.mp3)
$$
$$
Replace:\quad\1\n
$$
</div>

<div style="border: 2px solid black; padding: 10px; display: inline-block;">
$$
Find:(?<=\n)\s+
$$
$$
\text{Replace:(nothing)}
$$
</div>
The first find and replace removes the space at the begining and the second find replace splits the lines


#4

<div style="border: 2px solid black; padding: 10px; display: inline-block;">
$$
Find:(\d\{4\})\s(.*\.mp3)
$$
$$
Replace:\verb|\2_\1|
$$
</div>
Explanation:
This captures the 4-digit number and the space after the number and then the rest of the file name and then rearranges the captured parts to place the title and .mp3 first followed by the number at the end


#5
<div style="border: 2px solid black; padding: 10px; display: inline-block;">
$$
Find: (\w)(\w+),(\w+),(.+),(\d+)
$$

$$
Replace:\verb|\1_\3,\5|
$$
</div>

Explanation:
This captures the first letter of the first word, captures the rest of the first word, captures the entire second word, captures everything in third column, and captures only digits from 4th column. It replaces the first letter of the first word, inserts and underscore and then inserts the entire second word, inserta a comma then inserts the fourth column


#6
<div style="border: 2px solid black; padding: 10px; display: inline-block;">
$$
Find: (\w)(\w+),(\w{4})(\w+),(.+),(\d+)
$$

$$
Replace:\verb|\1_\3,\6|
$$
</div>

Explanation:
Captures the first letter of the first word, the rest of the first word, the first 4 letters of the second word, the rest of the second word, captures everything in third column, only digits from fourth column and replaces with the first letter of first word,inserts an underscore, insets penn, inserts a comma, and then the fourth column

#7
<div style="border: 2px solid black; padding: 10px; display: inline-block;">
$$
Find: ^(\w{3})\w+?,(\w{3})\w+?,([\d.]+),(\d+)
$$

$$
Replace:\1\2,\quad\4,\quad\3
$$
</div>

Explanation:
This captures the first 3 letters of the first word, the first 3 letters of the second word, the third column,the fourth column, and then combines first 3 letters of first and second words, inserts the last column and then inserts comma and space and third column

#8 
<div style="border: 2px solid black; padding: 10px; display: inline-block;">
$$
Find: \bNA\b
$$
$$
Replace: 0
$$
</div>

This fixes the pathogenbinary column so instead of 1 or 0, it is all numberic values, 0 or 1

<div style="border: 2px solid black; padding: 10px; display: inline-block;">

$$
Find: \verb|[-@!^+_%()\*#\$]+|
$$


$$
Replace: nothing
$$

</div>
This removes special characters from bombus_spp and host_plant columns

<div style="border: 2px solid black; padding: 10px; display: inline-block;">
$$
Find:\bworker|male\b\s?=\t
$$

$$
Replace: \1
$$
</div>
This removes the spaces after worker or male





