---
title: "Homework8"
output: html_document
date: "2025-03-19"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load necessary librarues
library(ggplot2)
library(MASS)
z <- read.table("cellular_biology.csv",header=TRUE,sep=",")
str(z)
summary(z)
```
Plot histogram of data
```{r}
# Plot histogram of cell diameters
p1 <- ggplot(data=z, aes(x=Cell_Diameter_um, y=..density..)) +
  geom_histogram(color="grey60", fill="cornsilk", size=0.2) +
  geom_density(linetype="dotted", size=0.75)  # Add empirical density curve
print(p1)
```
The histogram shows the distribution of the data. The empirical density curve helps visualize the spread and shape.

Fit statistical distribution

Fit a normal distribution
```{r}
normPars <- fitdistr(z$Cell_Diameter_um, "normal")
meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]

# Plot normal probability density
xval <- seq(0, max(z$Cell_Diameter_um), len=length(z$Cell_Diameter_um))
stat <- stat_function(aes(x = xval, y = ..y..), fun = dnorm, colour="red", 
                      n = length(z$Cell_Diameter_um), args = list(mean = meanML, sd = sdML))
p1 + stat
```
